version: "3.3"
services:
  db_mysql:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=admin_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres-data:/var/lib/postgresql